# Generated by Django 5.1.1 on 2025-02-11 22:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Medico', '0001_initial'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EliminacionFichaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador', models.CharField(max_length=255)),
                ('medico', models.CharField(max_length=255)),
                ('fecha_eliminacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AntecedenteEnfermedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fue_operado', models.BooleanField(blank=True, default=None, null=True)),
                ('toma_medicacion', models.BooleanField(blank=True, default=None, null=True)),
                ('estuvo_internado', models.BooleanField(blank=True, default=None, null=True)),
                ('sufre_hormigueos', models.BooleanField(blank=True, default=None, null=True)),
                ('es_diabetico', models.BooleanField(blank=True, default=None, null=True)),
                ('es_asmatico', models.BooleanField(blank=True, default=None, null=True)),
                ('es_alergico', models.BooleanField(blank=True, default=None, null=True)),
                ('alerg_observ', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('antecedente_epilepsia', models.BooleanField(blank=True, default=None, null=True)),
                ('desviacion_columna', models.BooleanField(blank=True, default=None, null=True)),
                ('dolor_cintura', models.BooleanField(blank=True, default=None, null=True)),
                ('fracturas', models.BooleanField(blank=True, default=None, null=True)),
                ('dolores_articulares', models.BooleanField(blank=True, default=None, null=True)),
                ('falta_aire', models.BooleanField(blank=True, default=None, null=True)),
                ('traumatismos_craneo', models.BooleanField(blank=True, default=None, null=True)),
                ('dolor_pecho', models.BooleanField(blank=True, default=None, null=True)),
                ('perdida_conocimiento', models.BooleanField(blank=True, default=None, null=True)),
                ('presion_arterial', models.BooleanField(blank=True, default=None, null=True)),
                ('muerte_subita_familiar', models.BooleanField(blank=True, default=None, null=True)),
                ('enfermedad_cardiaca_familiar', models.BooleanField(blank=True, default=None, null=True)),
                ('soplo_cardiaco', models.BooleanField(blank=True, default=None, null=True)),
                ('abstenerse_competencia', models.BooleanField(blank=True, default=None, null=True)),
                ('antecedentes_coronarios_familiares', models.BooleanField(blank=True, default=None, null=True)),
                ('fumar_hipertension_diabetes', models.BooleanField(blank=True, default=None, null=True)),
                ('fhd_observacion', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('consumo_cocaina_anabolicos', models.BooleanField(blank=True, default=None, null=True)),
                ('cca_observaciones', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('jugador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes', to='persona.jugador')),
            ],
            options={
                'db_table': 'antecedente_enfermedades',
            },
        ),
        migrations.CreateModel(
            name='RegistroMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('PROCESO', 'En proceso'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('VENCIDO', 'Vencido')], max_length=45, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('fecha_de_llenado', models.DateField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
                ('consentimiento_persona', models.BooleanField(blank=True, null=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_medicos', to='persona.jugador')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Medico.medico')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.torneo')),
            ],
            options={
                'db_table': 'ficha_registro',
            },
        ),
        migrations.CreateModel(
            name='OtrosExamenesClinicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respiratorio_observaciones', models.CharField(blank=True, default='Sin observaciones', max_length=200, null=True)),
                ('renal_observaciones', models.CharField(blank=True, default='Sin observaciones', max_length=200, null=True)),
                ('digestivo_observaciones', models.CharField(blank=True, default='Sin observaciones', max_length=200, null=True)),
                ('osteoarticular_observaciones', models.CharField(blank=True, default='Sin observaciones', max_length=200, null=True)),
                ('ficha_medica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otros_examenes', to='RegistroMedico.registromedico')),
            ],
        ),
        migrations.CreateModel(
            name='Oftalmologico',
            fields=[
                ('idoftalmologico', models.AutoField(primary_key=True, serialize=False)),
                ('od', models.CharField(blank=True, max_length=45, null=True)),
                ('oi', models.CharField(blank=True, max_length=45, null=True)),
                ('ficha_medica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RegistroMedico.registromedico')),
            ],
            options={
                'verbose_name': 'Examen Oftalmológico',
                'verbose_name_plural': 'Exámenes Oftalmológicos',
                'db_table': 'oftalmologico',
            },
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('idlaboratorio', models.AutoField(primary_key=True, serialize=False)),
                ('citologico', models.CharField(blank=True, default='S/D', max_length=45, null=True)),
                ('orina', models.CharField(blank=True, default='S/D', max_length=45, null=True)),
                ('colesterol', models.CharField(blank=True, default='S/D', max_length=45, null=True)),
                ('uremia', models.CharField(blank=True, default='S/D', max_length=45, null=True)),
                ('glucemia', models.CharField(blank=True, default='S/D', max_length=45, null=True)),
                ('otros', models.CharField(blank=True, default='S/D', max_length=45, null=True)),
                ('ficha_medica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RegistroMedico.registromedico')),
            ],
            options={
                'verbose_name': 'Examen de Laboratorio',
                'verbose_name_plural': 'Exámenes de Laboratorio',
                'db_table': 'laboratorio',
            },
        ),
        migrations.CreateModel(
            name='EstudiosMedico',
            fields=[
                ('idestudio', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_estudio', models.CharField(choices=[('ORINA', 'Análisis de Orina'), ('ELECTRO', 'Electrocardiograma'), ('ERGOMETRIA', 'Ergometría')], max_length=20)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='estudios/')),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('ficha_medica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RegistroMedico.registromedico')),
            ],
            options={
                'verbose_name': 'Estudio Médico',
                'verbose_name_plural': 'Estudios Médicos',
                'db_table': 'estudios_medicos',
            },
        ),
        migrations.CreateModel(
            name='ElectroEsfuerzo',
            fields=[
                ('idelectro_esfuerzo', models.AutoField(primary_key=True, serialize=False)),
                ('observaciones', models.CharField(blank=True, default='Sin observaciones', max_length=200, null=True)),
                ('ficha_medica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RegistroMedico.registromedico')),
            ],
            options={
                'verbose_name': 'Electro Esfuerzo',
                'verbose_name_plural': 'Electro Esfuerzos',
                'db_table': 'electro_esfuerzo',
            },
        ),
        migrations.CreateModel(
            name='ElectroBasal',
            fields=[
                ('idelectro_basal', models.AutoField(primary_key=True, serialize=False)),
                ('ritmo', models.CharField(blank=True, max_length=45, null=True)),
                ('PQ', models.CharField(blank=True, max_length=45, null=True)),
                ('frecuencia', models.CharField(blank=True, max_length=45, null=True)),
                ('arritmias', models.CharField(blank=True, max_length=45, null=True)),
                ('ejeQRS', models.CharField(blank=True, max_length=45, null=True)),
                ('trazadoNormal', models.CharField(blank=True, max_length=45, null=True)),
                ('observaciones', models.CharField(blank=True, default='Sin observaciones', max_length=45, null=True)),
                ('ficha_medica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RegistroMedico.registromedico')),
            ],
            options={
                'verbose_name': 'Electro Basal',
                'verbose_name_plural': 'Electro Basales',
                'db_table': 'electro_basal',
            },
        ),
        migrations.CreateModel(
            name='Cardiovascular',
            fields=[
                ('idcardiovascular', models.AutoField(primary_key=True, serialize=False)),
                ('auscultacion', models.CharField(blank=True, max_length=45, null=True)),
                ('soplos', models.CharField(blank=True, max_length=45, null=True)),
                ('R1', models.CharField(blank=True, max_length=45, null=True)),
                ('tension_arterial', models.CharField(blank=True, max_length=45, null=True)),
                ('R2', models.CharField(blank=True, max_length=45, null=True)),
                ('observaciones', models.CharField(blank=True, default='Sin observaciones', max_length=200, null=True)),
                ('ruidos_agregados', models.CharField(blank=True, max_length=45, null=True)),
                ('ficha_medica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RegistroMedico.registromedico')),
            ],
            options={
                'verbose_name': 'Examen Cardiovascular',
                'verbose_name_plural': 'Exámenes Cardiovasculares',
                'db_table': 'cardiovascular',
            },
        ),
        migrations.CreateModel(
            name='Torax',
            fields=[
                ('idtorax', models.AutoField(primary_key=True, serialize=False)),
                ('observaciones', models.CharField(blank=True, default='Sin observaciones', max_length=200, null=True)),
                ('ficha_medica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RegistroMedico.registromedico')),
            ],
            options={
                'verbose_name': 'Examen de Tórax',
                'verbose_name_plural': 'Exámenes de Tórax',
                'db_table': 'torax',
            },
        ),
    ]
