# Generated by Django 5.1.1 on 2025-03-21 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedentesCUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnet_vacunacion', models.BooleanField(default=False)),
                ('esquema_completo', models.BooleanField(default=False)),
                ('esquema_faltante', models.CharField(blank=True, max_length=255, null=True)),
                ('enfermedades_importantes', models.TextField(blank=True, null=True)),
                ('cirugias', models.CharField(blank=True, max_length=255, null=True)),
                ('cardiovasculares', models.CharField(blank=True, max_length=255, null=True)),
                ('trauma_funcional', models.CharField(blank=True, max_length=255, null=True)),
                ('condiciones_riesgo', models.CharField(blank=True, max_length=255, null=True)),
                ('medicamentos_prescriptos', models.CharField(blank=True, max_length=255, null=True)),
                ('cansancio_extremo', models.BooleanField(default=False)),
                ('falta_aire', models.BooleanField(default=False)),
                ('perdida_conocimiento', models.BooleanField(default=False)),
                ('palpitaciones', models.BooleanField(default=False)),
                ('precordialgias', models.BooleanField(default=False)),
                ('cefaleas', models.BooleanField(default=False)),
                ('vomitos', models.BooleanField(default=False)),
                ('otros', models.CharField(blank=True, max_length=255, null=True)),
                ('estudiante', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes', to='estudiante.estudiante')),
            ],
        ),
    ]
