# Generated by Django 5.1.1 on 2025-03-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0002_antecedentescus'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedentescus',
            name='alergias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='antecedentescus',
            name='asma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='antecedentescus',
            name='auditivos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='antecedentescus',
            name='chagas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='antecedentescus',
            name='diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='antecedentescus',
            name='hipertension',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='antecedentescus',
            name='neurologico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='antecedentescus',
            name='oftalmologicos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='antecedentescus',
            name='otras',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
