# Generated by Django 5.1.1 on 2025-03-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0003_antecedentescus_alergias_antecedentescus_asma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedentescus',
            name='declaracion_jurada',
            field=models.BooleanField(default=False),
        ),
    ]
