# Generated by Django 5.1.1 on 2025-04-16 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0005_alter_estudiante_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedentescus',
            name='estudiante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes', to='estudiante.estudiante'),
        ),
    ]
