# Generated by Django 5.1.1 on 2025-02-11 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_consultorio', models.CharField(blank=True, max_length=15, null=True)),
                ('firma', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medico', to='account.profile')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'db_table': 'medico',
            },
        ),
    ]
