# Generated by Django 5.1.1 on 2025-05-08 19:36

import Medico.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificado_matricula', models.FileField(blank=True, null=True, upload_to=Medico.models.upload_to_matricula)),
                ('certificado_firma_electronica', models.FileField(blank=True, null=True, upload_to=Medico.models.upload_to_firma)),
                ('url_certificado', models.URLField(blank=True, null=True)),
                ('qr_valido', models.BooleanField(default=False)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('medico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documentacion', to='Medico.medico')),
            ],
        ),
    ]
