# Generated by Django 5.1.1 on 2025-05-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medico', '0002_documentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='contrato_aceptado',
            field=models.BooleanField(default=False),
        ),
    ]
