# Generated by Django 5.1.1 on 2025-03-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rol',
            field=models.CharField(choices=[('jugador', 'Jugador'), ('medico', 'Médico'), ('representante', 'Representante'), ('estudiante', 'estudiante')], default='jugador', max_length=20),
        ),
    ]
