# Generated by Django 5.1.1 on 2025-04-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_options_alter_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rol',
            field=models.CharField(choices=[('jugador', 'Jugador'), ('medico', 'Médico'), ('representante', 'Representante'), ('colegio', 'Colegio'), ('estudiante', 'Estudiante')], default='jugador', max_length=20),
        ),
    ]
