# Generated by Django 5.1.1 on 2025-04-10 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Representate', '0001_initial'),
        ('account', '0004_alter_profile_rol'),
        ('estudiante', '0005_alter_estudiante_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepresenteColegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='representante_colegio', to='account.profile')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representantes_colegio', to='estudiante.colegio')),
            ],
        ),
    ]
