# Generated by Django 5.1.1 on 2025-03-22 15:07

import Cus.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Medico', '0001_initial'),
        ('estudiante', '0004_antecedentescus_declaracion_jurada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('PROCESO', 'En proceso'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('VENCIDO', 'Vencido')], max_length=45, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('fecha_de_llenado', models.DateField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
                ('consentimiento_persona', models.BooleanField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cus', to='estudiante.estudiante')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Medico.medico')),
            ],
            options={
                'db_table': 'cus_ficha_medica',
            },
        ),
        migrations.CreateModel(
            name='ComentarioDerivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios y/o derivaciones')),
                ('recomendaciones', models.TextField(blank=True, null=True, verbose_name='Se recomienda')),
                ('cus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='Cus.cus')),
            ],
            options={
                'verbose_name': 'Comentarios y Derivaciones',
                'verbose_name_plural': 'Comentarios y Derivaciones',
                'db_table': 'comentarios_derivaciones',
            },
        ),
        migrations.CreateModel(
            name='AlimentacionNutricion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicita_plan_especial', models.BooleanField(blank=True, null=True)),
                ('tipo_plan', models.CharField(blank=True, help_text='Especificar si se solicita plan especial', max_length=200, null=True)),
                ('cus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alimentacion', to='Cus.cus')),
            ],
            options={
                'verbose_name': 'Alimentación y Nutrición',
                'verbose_name_plural': 'Alimentación y Nutrición',
                'db_table': 'alimentacion_nutricion',
            },
        ),
        migrations.CreateModel(
            name='EstudioCus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_estudio', models.CharField(choices=[('ELECTRO', 'Electrocardiograma'), ('OTROS', 'Otros Estudios')], max_length=20)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='estudios_cus/')),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_caducidad', models.DateField(default=Cus.models.default_fecha_caducidad)),
                ('cus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='Cus.cus')),
            ],
            options={
                'verbose_name': 'Estudio CUS',
                'verbose_name_plural': 'Estudios CUS',
                'db_table': 'estudios_cus',
            },
        ),
        migrations.CreateModel(
            name='ExamenAbdomen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalles', models.TextField(blank=True, null=True)),
                ('cus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abdomen', to='Cus.cus')),
            ],
            options={
                'verbose_name': 'Examen Abdomen',
                'verbose_name_plural': 'Exámenes Abdomen',
                'db_table': 'examen_abdomen',
            },
        ),
        migrations.CreateModel(
            name='ExamenCardiovascular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auscultacion', models.CharField(blank=True, max_length=255, null=True)),
                ('arritmia', models.CharField(blank=True, max_length=255, null=True)),
                ('soplos', models.CharField(blank=True, max_length=255, null=True)),
                ('tension_arterial', models.CharField(blank=True, max_length=50, null=True)),
                ('cus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cardiovascular', to='Cus.cus')),
            ],
            options={
                'verbose_name': 'Examen Cardiovascular',
                'verbose_name_plural': 'Exámenes Cardiovasculares',
                'db_table': 'examen_cardiovascular',
            },
        ),
        migrations.CreateModel(
            name='ExamenEndocrinologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalles', models.TextField(blank=True, null=True)),
                ('cus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endocrino', to='Cus.cus')),
            ],
            options={
                'verbose_name': 'Examen Endocrinológico',
                'verbose_name_plural': 'Exámenes Endocrinológicos',
                'db_table': 'examen_endocrinologico',
            },
        ),
        migrations.CreateModel(
            name='ExamenFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kilogramos', max_digits=5, null=True)),
                ('talla', models.DecimalField(blank=True, decimal_places=2, help_text='Talla en centímetros', max_digits=5, null=True)),
                ('imc', models.DecimalField(blank=True, decimal_places=2, help_text='Índice de masa corporal', max_digits=5, null=True)),
                ('diagnostico_antropometrico', models.CharField(blank=True, max_length=200, null=True)),
                ('cus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examen_fisico', to='Cus.cus')),
            ],
            options={
                'verbose_name': 'Examen Físico',
                'verbose_name_plural': 'Exámenes Físicos',
                'db_table': 'examen_fisico',
            },
        ),
        migrations.CreateModel(
            name='ExamenFonoaudiologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalles', models.TextField(blank=True, null=True)),
                ('cus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fonoaudiologico', to='Cus.cus')),
            ],
            options={
                'verbose_name': 'Examen Fonoaudiológico',
                'verbose_name_plural': 'Exámenes Fonoaudiológicos',
                'db_table': 'examen_fonoaudiologico',
            },
        ),
        migrations.CreateModel(
            name='ExamenGenitourinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menarca', models.BooleanField(blank=True, null=True)),
                ('turner', models.BooleanField(blank=True, null=True)),
                ('cus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='genitourinario', to='Cus.cus')),
            ],
            options={
                'verbose_name': 'Examen Genitourinario',
                'verbose_name_plural': 'Exámenes Genitourinarios',
                'db_table': 'examen_genitourinario',
            },
        ),
        migrations.CreateModel(
            name='ExamenNeurologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalles', models.TextField(blank=True, null=True)),
                ('cus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='neurologico', to='Cus.cus')),
            ],
            options={
                'verbose_name': 'Examen Neurológico',
                'verbose_name_plural': 'Exámenes Neurológicos',
                'db_table': 'examen_neurologico',
            },
        ),
        migrations.CreateModel(
            name='ExamenOdontologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalles', models.TextField(blank=True, null=True)),
                ('cus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odontologico', to='Cus.cus')),
            ],
            options={
                'verbose_name': 'Examen Odontológico',
                'verbose_name_plural': 'Exámenes Odontológicos',
                'db_table': 'examen_odontologico',
            },
        ),
        migrations.CreateModel(
            name='ExamenOftalmologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agudeza_visual_der', models.CharField(blank=True, max_length=20, null=True)),
                ('agudeza_visual_izq', models.CharField(blank=True, max_length=20, null=True)),
                ('usa_anteojos', models.BooleanField(blank=True, null=True)),
                ('otros', models.CharField(blank=True, max_length=255, null=True)),
                ('cus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oftalmologico', to='Cus.cus')),
            ],
            options={
                'verbose_name': 'Examen Oftalmológico',
                'verbose_name_plural': 'Exámenes Oftalmológicos',
                'db_table': 'examen_oftalmologico',
            },
        ),
        migrations.CreateModel(
            name='ExamenOsteoarticular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columna_normal', models.BooleanField(blank=True, null=True)),
                ('cifosis', models.BooleanField(blank=True, null=True)),
                ('lordosis', models.BooleanField(blank=True, null=True)),
                ('escoliosis', models.BooleanField(blank=True, null=True)),
                ('miembros_superiores', models.TextField(blank=True, null=True)),
                ('miembros_inferiores', models.TextField(blank=True, null=True)),
                ('cus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='osteoarticular', to='Cus.cus')),
            ],
            options={
                'verbose_name': 'Examen Osteoarticular',
                'verbose_name_plural': 'Exámenes Osteoarticulares',
                'db_table': 'examen_osteoarticular',
            },
        ),
        migrations.CreateModel(
            name='ExamenPiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalles', models.TextField(blank=True, null=True)),
                ('cus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='piel', to='Cus.cus')),
            ],
            options={
                'verbose_name': 'Examen de Piel y T.C.S.C.',
                'verbose_name_plural': 'Exámenes de Piel y T.C.S.C.',
                'db_table': 'examen_piel_tcsc',
            },
        ),
        migrations.CreateModel(
            name='ExamenRespiratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalles', models.TextField(blank=True, null=True)),
                ('cus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='respiratorio', to='Cus.cus')),
            ],
            options={
                'verbose_name': 'Examen Respiratorio',
                'verbose_name_plural': 'Exámenes Respiratorios',
                'db_table': 'examen_respiratorio',
            },
        ),
        migrations.CreateModel(
            name='Recomendaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalles', models.TextField(blank=True, null=True)),
                ('cus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='Cus.cus')),
            ],
            options={
                'verbose_name': 'Recomendaciones',
                'verbose_name_plural': 'Recomendaciones',
                'db_table': 'recomendaciones',
            },
        ),
    ]
