# Generated by Django 5.1.1 on 2025-04-12 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cus', '0002_alter_examengenitourinario_turner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarioderivacion',
            name='recomendaciones',
        ),
        migrations.CreateModel(
            name='ActualizacionCUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('talla', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('diagnostico_antropometrico', models.CharField(blank=True, max_length=200)),
                ('antecedentes', models.TextField(blank=True)),
                ('examen_fisico', models.TextField(blank=True)),
                ('estado_salud', models.CharField(choices=[('Normal', 'Normal'), ('Derivado', 'Derivado')], max_length=20)),
                ('derivado_a', models.CharField(blank=True, max_length=200)),
                ('debe_volver', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('cus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualizaciones', to='Cus.cus')),
            ],
        ),
    ]
