# Generated by Django 5.1.1 on 2025-04-13 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cus', '0003_remove_comentarioderivacion_recomendaciones_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActualizacionCUS',
        ),
    ]
