# Generated by Django 5.1.1 on 2025-04-13 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cus', '0004_delete_actualizacioncus'),
        ('Medico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualizacionCUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('lugar', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('talla', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('diagnostico_antropometrico', models.CharField(blank=True, max_length=200, null=True)),
                ('antecedentes', models.TextField(blank=True)),
                ('examen_fisico', models.TextField(blank=True)),
                ('estado_salud_normal', models.BooleanField(default=True)),
                ('derivado_a', models.CharField(blank=True, max_length=100)),
                ('debe_volver', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('cus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualizaciones', to='Cus.cus')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualizaciones_realizadas', to='Medico.medico')),
            ],
            options={
                'verbose_name': 'Actualización CUS',
                'verbose_name_plural': 'Actualizaciones CUS',
                'ordering': ['-fecha'],
            },
        ),
    ]
