# Generated by Django 5.1.1 on 2025-04-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cus', '0005_actualizacioncus'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualizacioncus',
            name='vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
